pipeline:
  
  build:
    image: alpine:latest
    commands:
      - apk update ; apk add tar
      - touch dist.tar.gz ; tar --exclude=dist.tar.gz -cvzf dist.tar.gz .
        
  deploy:
    image: appleboy/drone-scp
    host: 108.61.123.246
    port: 22
    secrets: [ ssh_password , ssh_username ]
    source: dist.tar.gz
    target: /home/user/goldiam.io
  
  extract:
    image: appleboy/drone-ssh
    host: 108.61.123.246
    port: 22
    command_timeout: 600
    secrets: [ ssh_password , ssh_username ]
    script:
      - cd /home/user/goldiam.io ;
       tar -xvzf dist.tar.gz; rm dist.tar.gz ;
       yarn; yarn build;
       cp -a /home/user/goldiam.io/dist/. /var/www/html/ ; exit
    when:
      branch: dev