pipeline:
  build:
    image: alpine:latest
    commands:
      - apk update ; apk add tar
      - touch dist.tar.gz ; tar --exclude=dist.tar.gz -cvzf dist.tar.gz .
  deploy:
    image: appleboy/drone-scp
    host: 108.61.123.246
    port: 22
    secrets: [ ssh_password , ssh_username ]
    source: dist.tar.gz
    target: /home/user/webpack-static-template
  extract:
    image: appleboy/drone-ssh
    host: 108.61.123.246
    port: 22
    command_timeout: 600
    secrets: [ ssh_password , ssh_username ]
    script:
      - cd /home/user/webpack-static-template;
       tar -xvzf dist.tar.gz;
       rm dist.tar.gz;
       yarn;
       yarn build;
       rm -rf /var/www/html/*;
       cp -a /home/user/webpack-static-template/dist/. /var/www/html/; exit
+branches: develop

pipeline:
  build:
    image: alpine:latest
    commands:
      - apk update ; apk add tar
      - touch dist.tar.gz ; tar --exclude=dist.tar.gz -cvzf dist.tar.gz .
  deploy:
    image: appleboy/drone-scp
    host: 108.61.123.246
    port: 22
    secrets: [ ssh_password , ssh_username ]
    source: dist.tar.gz
    target: /home/user/webpack-static-template
  extract:
    image: appleboy/drone-ssh
    host: 108.61.123.246
    port: 22
    command_timeout: 600
    secrets: [ ssh_password , ssh_username ]
    script:
      - echo "ADFSAFJASLKFJJSFKA"
      # - cd /home/user/webpack-static-template;
      #  tar -xvzf dist.tar.gz;
      #  rm dist.tar.gz;
      #  yarn;
      #  yarn build;
      #  rm -rf /var/www/html/*;
      #  cp -a /home/user/webpack-static-template/dist/. /var/www/html/; exit
+branches: master


    # extract_prod:
    # image: appleboy/drone-ssh
    # host: 108.61.123.246
    # port: 22
    # command_timeout: 600
    # secrets: [ ssh_password , ssh_username ]
    # script:
    #   echo "Aaaa"
    #   # - cd /home/user/webpack-static-template;
    #   #  tar -xvzf dist.tar.gz;
    #   #  rm dist.tar.gz;
    #   #  yarn;
    #   #  yarn build;
    #   #  rm -rf /var/www/html/*;
    #   #  cp -a /home/user/webpack-static-template/dist/. /var/www/html/; exit
    # when:
    #   branch: [master]